### ISSUE TITLE
How to train using 2D RGB X-ray images

### ISSUE THREAD

**Issue by jaykshirsagar05** [caiyuanhao1998/SAX-NeRF#13]
Is it possible to use this framework on 2D RGB X-ray images instead of CT scans? 

Here are my data specifications and I want to know if it is sensible and possible to train it using your designs:
1. Collection of 2D rgb xray images
2. Lacks camera parameters
3. Dynamic in nature

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. Actually, our method is trained on 2D X-ray images instead of CT scans.

If you want to train on your collected 2D RGB x-ray images, the first step is to compute the camera poses for your images. There are two open-source tools for you to use:

DusT3R : https://github.com/naver/dust3r

COLMAP (SfM) : https://github.com/colmap/colmap

Wish this information could help you
