### ISSUE TITLE
About line size of the Lineformer

### ISSUE THREAD

**Issue by Henryzyf** [caiyuanhao1998/SAX-NeRF#14]
In all the config files of the experiments, you set the line size as 2 for the Lineformer network, which means only the self-attention between 2 points is considered. I also try line size 4 and 8, but actually 2 is best. However, it is counter-intuitive  and strange that self-attention between 2 points is good enough for reconstruction. Generally, I think more points considered will achieve better results. Can you explain why you choose 2 as the line size?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. This is because the radiodensity of the scanned object changes sharply. As analyzed in our paper, naively computes the self-attention along the whole ray cannot capture the intra-object dependencies. Thus, the statement that the line size bigger the performance better is wrong. Hope this information may help.
