### ISSUE TITLE
SAX-NeRF Testing

### ISSUE THREAD

**Issue by kbhyun12** [caiyuanhao1998/SAX-NeRF#15]
Hello. 
I am encountering an error while testing with test.py. It seems to be a compilation-related message. How should I resolve it?
![1](https://github.com/user-attachments/assets/1adb78bb-6bfe-42e5-bfe2-25d51db1607d)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. 

This error message shows a problem related to checking the compiler version in `torch.utils.cpp_extension`. Specifically, the error occurred when attempting to use the `where` command to locate the `cl` compiler, which returned a non-zero exit status, indicating that the `cl` command was not found. This typically means that the Visual C++ compiler is not correctly installed or its path is not added to the environment variables.

Here are my suggestions to fix this bug:

1. Confirm Visual Studio and C++ Tools Installation: Ensure that Visual Studio is installed on your computer, and that you selected the C++ desktop development environment during installation.
2. Check Environment Variables: Make sure the path to the Visual C++ compiler (usually something like C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\<version>\bin\Hostx64\x64) is added to your system's environment variables.
3. Reopen Command Line: After installing or modifying environment variables, reopen your command line window to ensure the updates are applied.
4. Check Python Package Dependencies: Ensure your torch and related dependencies are up to date, as older versions of libraries can have compatibility issues.

In general, I do not suggest you use Windows system to execute the code because windows system usually cause many weird bugs. It is much better to use Ubuntu system.

If you find our repo useful, please help us star it, thanks!
