### ISSUE TITLE
About the instant-ngp

### ISSUE THREAD

**Issue by edural** [caiyuanhao1998/SAX-NeRF#33]
Hello, I'm glad to try your work. Currently, I have an issue that seems to be related to a compilation error of `_hash_encoder`. Based on your previous issue, it seems like the problem is due to a missing `instant-ngp` module. I've tried several times but still can't resolve it successfully. Could you please guide me on how to correctly install the `instant-ngp` encoder? Thank you very much!

My environment is exactly the same as the one you provided
cuda：11.3
pytorch：1.11.0
wsl2   Ubuntu24.04
RTX 4070s

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

The `instant-ngp` module is compiled in the first run. I suggest you follow our `README.MD` to install the environment. Check all the package versions because I have re-installed them and successfully ran the code.

If you find our repo useful, please help us star it, thanks :)
